[workspace]
resolver = "2"
members = [
  "crates/*",
  "examples/*",
  "tools/*"
]

[workspace.package]
edition = "2021"

[workspace.dependencies]
# internal
haste = { path = "." }
haste_core = { path = "crates/haste_core" }
haste_protos = { path = "crates/haste_protos" }
haste_vartype = { path = "crates/haste_vartype" }
# external
anyhow = "1.0.86"
# NOCOMMIT
# dungers = { git = "https://github.com/blukai/dungers.git", rev = "d14d436bc6fb5c4d8cdb003db57b5738531a4220", features = ["charsor", "varint", "bitbuf", "rangealloc"] }
dungers = { path = "../dungers", features = ["charsor", "varint", "bitbuf", "rangealloc"] }
dyn-clone = "1.0.17"
expect-test = "1.5.0"
hashbrown = { version = "0.14.5", default-features = false, features = ["inline-more"]  }
lazy_static = "1.5.0"
nohash = "0.2.0"
prost = "0.13.2"
prost-build = "0.13.2"
protobuf-src = "2.1.0"
rand = "0.8.5"
snap = "1.1.1"
thiserror = "1.0.63"
which = "6.0.3"

[package]
name = "haste"
version = "0.0.0"
edition.workspace = true

[dependencies]
haste_core.workspace = true

[features]
deadlock = ["haste_core/deadlock"]
dota2 = ["haste_core/dota2"]
# TODO(blukai): rename preserve-metadata feature into something more meaningful,
# or get rid of it all together and preserve symbols only in debug builds.
preserve-metadata = ["haste_core/preserve-metadata"]
