[workspace]
resolver = "2"
members = [
  "crates/*",
  "examples/*",
  "tools/*"
]

[workspace.package]
edition = "2021"

[workspace.dependencies]
# internal
haste = { path = "." }
haste_core = { path = "crates/haste_core" }
haste_vartype = { path = "crates/haste_vartype" }
# external
anyhow = "1.0.86"
dungers = { git = "https://github.com/blukai/dungers.git", rev = "5419784ef771089369bdce5463a6cf6da35d3a79", features = ["charsor", "varint", "bitbuf"] }
dyn-clone = "1.0.17"
expect-test = "1.5.0"
hashbrown = { version = "0.14.5", default-features = false, features = ["inline-more"]  }
lazy_static = "1.5.0"
nohash = "0.2.0"
rand = "0.8.5"
snap = "1.1.1"
thiserror = "1.0.64"
valveprotos = { git = "https://github.com/blukai/valveprotos-rs.git", rev = "0d6c6b72ad469db3841d1afd36804fe9043ef7ce" }
which = "6.0.3"

[package]
name = "haste"
version = "0.0.0"
edition.workspace = true

[dependencies]
haste_core.workspace = true

[features]
deadlock = ["haste_core/deadlock"]
dota2 = ["haste_core/dota2"]
# TODO(blukai): rename preserve-metadata feature into something more meaningful,
# or get rid of it all together and preserve symbols only in debug builds.
preserve-metadata = ["haste_core/preserve-metadata"]
protobuf-src = ["haste_core/protobuf-src"]

# enable more optimizations in dev (/debug) builds for dependencies
[profile.dev.package."*"]
opt-level = 3
