[workspace]
resolver = "2"
members = [
  "crates/*",
  "examples/*",
  "tools/*"
]

[workspace.package]
edition = "2021"

[workspace.dependencies]
# internal
haste = { path = "crates/haste" }
haste_protos = { path = "crates/haste_protos" }
haste_vartype = { path = "crates/haste_vartype" }
# external
anyhow = "1.0.86"
dungers = { git = "https://github.com/blukai/dungers.git", rev = "e88fe5d31d0806a6ebac3aa3d8f54dcba07400f1", features = ["charsor", "varint", "bitbuf"] }
dyn-clone = "1.0.17"
expect-test = "1.5.0"
hashbrown = { version = "0.14.5", default-features = false, features = ["inline-more"]  }
nohash = "0.2.0"
prost = "0.13.2"
prost-build = "0.13.2"
protobuf-src = "2.1.0"
rand = "0.8.5"
snap = "1.1.1"
thiserror = "1.0.63"
which = "6.0.3"

