[package]
name = "uniquetypes"
version = "0.0.0"
edition.workspace = true

[dependencies]
anyhow.workspace = true
dungers = { workspace = true, features = ["varint"] }
haste.workspace = true
haste_vartype.workspace = true
