[package]
name = "uniquetypes"
version = "0.0.0"
edition.workspace = true

[dependencies]
anyhow.workspace = true
# my other repose
varint.workspace = true
# workspace
haste.workspace = true
haste_vartype.workspace = true
