[package]
name = "haste_vartype"
version = "0.0.0"
edition.workspace = true

[dependencies]
thiserror.workspace = true
# my other repos
charsor.workspace = true

[dev-dependencies]
expect-test.workspace = true
